### PR TITLE
put api specification into the Docker image (API publication) (#94)

### LINKED ISSUE #94: Publish the API specification
as required by https://opensource.zalando.com/restful-api-guidelines/#192

### PR DESCRIPTION
**Pull request by maxim-tschumak**
Closes #94

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
@juhmelo @mrandi  @harti2006 please have a look

**Comment by mrandi** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
Thanks, Michele!

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
